### ISSUE TITLE
Silent crash saving models with validations

### ISSUE THREAD

**Issue by skandragon** [infinitered/cdq#12]
I am not yet sure if this is a problem with cdq, or RubyMotion.

I have a model with a string field called "name", and am attempting to write a validation for it.  However, when cdq.save is called, the application silently exits (according to the console)

``` ruby
class Tag < CDQManagedObject
  def validateName(valuePointer, error: errorPtr)
    puts valuePointer[0].inspect
    true
  end
end
```

It works so long as I don't actually touch valuePointer in any way.  it will crash with any of these:

``` ruby
puts valuePointer.inspect
puts valuePointer[0].inspect
NSLog(@"%@", valuePointer)
NSLog(@"%@", valuePointer[0])
```

**Comment by Sohair63** [comment]
Iam writing this in my model.
> emp = Employee.where(:name).eq("ipsum")
 emp.email

and getting the following error

>> targeted_query.rb:154:in `method_missing:': undefined method `email' for #<CDQ::CDQTargetedQuery:0x10fd3f9d0 ...> (NoMethodError)


How can I access model attributes ?
