### ISSUE TITLE
How to use cdq to connect to sqlite

### ISSUE THREAD

**Issue by Jusliang** [infinitered/cdq#120]
Hi there, 
I am trying to application like dictionary, which need to load some data predefined in the database to the view.  And I am planning to use sqlite to store all the data. 

So, is it possible to connect to sqlite database or other database by cdq? 
And Map SQLite data to Ruby objects?
Much appreciate if someone can guide me how to implement this!

**Comment by kemiller** [comment]
You cannot in general connect core data to an arbitrary SQLite database.  If you want to use it, you'd need to pull your data out of your database ahead of time, and then load it into CoreData models, and then save the generated files.  That's about all I know.  Good luck!
