### ISSUE TITLE
Disappearing context

### ISSUE THREAD

**Issue by jelmerderonde** [infinitered/cdq#126]
I'm using RedPotion 1.5.0 which includes CDQ 1.0.8 and the latest version of the AWS SDK which includes (a renamed version of) the [Bolts](https://github.com/BoltsFramework/Bolts-ObjC) framework.

In my Project < CDQManagedObject class the entire CDQ stack seems to vanish after a Bolts succes block. I will include a little bit of code to illustrate:

```ruby
class Project < CDQManagedObject

...
      def fetch
            get_project(self.parse_object_id).continueWithSuccessBlock(lambda do |task|
                  @project = task.result
                  self.title = @project['title']
                  self.key = @project['key']
                  self.size = @project['size']

                  app.data.save

                  mp "1:"
                  mp app.data.contexts.current
                  return download_package(self.key)
                end).continueWithSuccessBlock(lambda do |task|
                  mp "2:"
                  mp app.data.contexts.current
      end
...
end
```

Output of this is:
`"1:"`
`#<NSManagedObjectContext:0x112c34ac0>`
`"2:"`
`nil`

Maybe I'm doing something colossally wrong but I can't get it fixed. I would appreciate any help.

**Comment by kemiller** [comment]
Can you tell what thread they are running on?

**Comment by kemiller** [comment]
Also, what does it mean to have more than one success block?

**Comment by jelmerderonde** [comment]
Using NSThread.currentThread the `app.data.contexts.current`'s appear to be on different threads.

**Comment by jelmerderonde** [comment]
in the first succesblock I return a new task. If that is also succesful the next block is called.

**Comment by kemiller** [comment]
If you're on a new thread, it won't have a context stack set up.  Some info here:  https://github.com/infinitered/cdq/wiki/New-Threading-and-Context-Stack-model
