### ISSUE TITLE
Accessor problems in 10.12 and xcode 8

### ISSUE THREAD

**Issue by markrickert** [infinitered/cdq#136]
> CoreData: warning: dynamic accessors failed to find @property implementation for 'user_connected' for entity Conversation while resolving selector 'user_connected' on class 'Conversation'.  Did you remember to declare it @dynamic or @synthesized in the @implementation ?

This has shown up after the update to Xcode 8 on Sierra.

**Comment by markrickert** [comment]
This is actually a problem with the code that's generated by `ruby-xcdm`

**Comment by markrickert** [comment]
Fixed here: https://github.com/infinitered/ruby-xcdm/issues/21

**Comment by digitalmoksha** [comment]
Hey Mark, thanks for tackling this issue.  However this is still occurring for me.  After updating to the latest `ruby-xcdm`, deleting the `resources/CDQ.momd` and `resources/CDQ.xcdatamodeld` files, and `rake clean:all`, the `rake spec` still gives errors like:

```
Timestamp Update Case
  - should not set created_at
CoreData: warning: dynamic accessors failed to find @property implementation for 'flag' for entity Timestamp while resolving selector 'setFlag:' on class 'Timestamp'.  Did you remember to declare it @dynamic or @synthesized in the @implementation ?
```

I verified the generated `CDQ.xcdatamodeld` had the new `codeGenerationType="class"`

**Comment by markrickert** [comment]
Interesting, @digitalmoksha... the fix to `ruby-xcdm` did it for me. I'm not seeing these warnings anymore. There might be another XML property that Xcode 8 added that I didn't factor in.

But it's fixed on my end. Any idea what might be causing the issue over there?

**Comment by digitalmoksha** [comment]
Nope, no idea why it's happening.  I copied an XCode 8 generated header, and that didn't have any effect.  The cdq tests consistently produce the warning
