### ISSUE TITLE
[ci] Travis CI failing

### ISSUE THREAD

**Issue by cmckni3** [infinitered/cdq#142]
```
sudo chown -R travis ~/Library/RubyMotion
chown: /Users/travis/Library/RubyMotion: No such file or directory
The command "sudo chown -R travis ~/Library/RubyMotion" failed and exited with 1 during .
```

**Comment by andrewhavens** [comment]
The error was before that line:
```
$ motion --version
/Users/travis/.travis/functions: line 109: motion: command not found
```
Looks like RubyMotion isn't being installed correctly.

**Comment by andrewhavens** [comment]
Based on another working Travis build, I think the thing we're missing in the travis config is `osx_image: xcode8`

**Comment by cmckni3** [comment]
Yeah true it was the line before too. Either way RM isn't installed.

I know Travis CI changed up stuff since introducing containers

https://docs.travis-ci.com/user/languages/objective-c#supported-xcode-versions
