### ISSUE TITLE
Cannot get gem to work

### ISSUE THREAD

**Issue by dkrusenstrahle** [infinitered/cdq#2]
Hello,

First off, thanks for creating such a cool gem!

I try to use it but I get the below error:

reason: 'uninitialized constant CDQManagedOjbect (NameError)
1. I have added CDQ to gem file and ran bundle.
2. I have ran cdq init.
3. I have added include CDQ and cdq.setup to Appdelegate.

I am using the Promotion gem. Could that be a problem?

**Comment by Sohair63** [comment]
I am having this error. 
This was running ok few days back.
Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant CDQManagedObject (NameError)

**Comment by GantMan** [comment]
I'm seeing this more and more often in RM 3. It might need a clean all and build in correct order.  See my newclear gem. Please let me know if that fixes.

**Comment by Sohair63** [comment]
it was the problem with rake command.
I had installed rails.

i used
> bundle exec rake devise

this worked. as it used local rake not the system's.

On Monday, 12 January 2015, Gant Laborde <notifications@github.com> wrote:

> I'm seeing this more and more often in RM 3. It might need a clean all and
> build in correct order. See my newclear gem. Please let me know if that
> fixes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinitered/cdq/issues/2#issuecomment-69584043>.
>


-- 


Regards,

Sohair Ahmad.
