### ISSUE TITLE
Example of using cdq as a datasource for a table view?

### ISSUE THREAD

**Issue by skandragon** [infinitered/cdq#5]
I'm searching for a full featured yet tableview data source compatible core data wrapper.  So far, the ones I like seem to not support tableview, and the ones I dislike do.  :)

Is there an example of how to use cdq, complete with table view sectioning and so forth, without loading all records?

Thanks!

**Comment by buley** [comment]
This would be hugely useful to me. 

If anyone has one, even just a gist of a working implementation would be very helpful.

**Comment by kemiller** [comment]
@buley I don't have an example, but NSFetchedResultsController is probably the right way if your table consists solely of CD data.  Otherwise, just simple array access is enough.  @skandragon do you have any sample code you can share?

**Comment by willrax** [comment]
Here's a quick example for you @buley https://gist.github.com/willrax/6f937dab5aa7dc804607

**Comment by buley** [comment]
@willrax this `NSFetchedResultsController` is exactly what I needed, thank you. As @kemiller pointed out `.rows` works fine but as I using only CoreData managed objects I am wondering if I can improve my memory footprint by using `NSFetchedResultsController`. Thanks to both of you for this excellent community support.
