### ISSUE TITLE
Ability to Rollback Changes

### ISSUE THREAD

**Issue by dmarkow** [infinitered/cdq#60]
Right now there's no direct way to roll back a model to its persisted state, as far as I can tell (short of not calling `cdq.save`, but it looks like the changed data is still cached until relaunching the app). The workaround I'm using now is calling `cdq.contexts.current.rollback`, though that rolls back the entire context instead of just one model.

Not sure if this is possible to implement, or if I'm missing something obvious?

**Comment by kemiller** [comment]
The only reason I'd be hesitant to do that is that it doesn't behave quite like save does, and the current way isn't all that arduous.  If you or someone is motivated, feel free to submit a pull request.  :smile:
