### ISSUE TITLE
Question: CDQ and RestKit

### ISSUE THREAD

**Issue by matthewsinclair** [infinitered/cdq#68]
I'm doing some work with `CDQ` and `RestKit` and I'm trying to come up with a way to quickly and easily build all of the appropriate request and response mappers that RestKit needs. I'm working on a gem with the working title of `Restikle` that I hope can make this job a bit easier, especially for people who want to connect a RubyMotion app to a RESTful Rails back-end, using `CoreData` and `CDQ` on the device as a local model repository.

My goal is to be able to provide my `Restikle::Instrumentor` class the output of `rake routes` from the Rails project, and then either `db/schema.rb` (from the Rails project) or `resources/<cdq_schema.rb>` (from the RubyMotion+CDQ project) and then have `Instrumentor` automatically configure `RestKit` with all of the correct request and response mappers.

This would avoid the vast amount of boilerplate that `RestKit` seems to need to do even the simplest thing.

I've made some good progress, but the bit that I am looking for some clues on is how to inflect the attributes for a particular CDQ model entity so that I can build the appropriate `RestKit` `RKEntityMapping`s for each attribute of the entity. I want `Restikle` to be able to create these mappings automatically from the data that I have available, after parsing the routes and schema files. 

Given a CDQ entity, is there a way to get the attributes for that entity? And what about relationships between CDQ entities (like one-to-many, etc). 

I have had a look around and I can't find anything that makes the `RestKit` configuration any easier. It just seems like everyone who uses `RestKit` is ok with all of the boilerplate. Apologies in advance if I have missed something obvious that makes this kind of thing easier, but I just can't find it. 

The REST back-end that I am talking is a very rich e-commerce platform with many resources and many more routes. So my motivation here is to avoid what is quite literally, thousands of lines of boilerplate code to configure RestKit. 

I'll be more than happy to publish the `Restikle` gem if I can get this working, because I just can't be the only person labouring with this kind of *Ruby-Motion / RestKit / RESTful Rails* challenge. 

Any help much appreciated.

**Comment by matthewsinclair** [comment]
Ok, so I have almost finished building my `restikle` gem, which is, as discussed above, an easy way to generate a `cdq` schema from a Rails `schema.rb` file, as well as an auto-magic RestKit configuration utility that allows you to easily build the RestKit mappings necessary to support the resources defined by the output of `rake routes` from a Rails project. As soon as I have this last bit working, I'll put it up onto GitHub for people to have a play with. 

However, I have an issue at the moment where I am getting an SQLite 522 error when I try to access an entity. For example, consider this spec:

```
  it 'should allow a not-so-simple (nested) get call to the back-end (countries/1)' do
    @rsmgr.should != nil

    @status = :unknown
    @country = Country.where(:id).eq(1).first
    Dispatch::Queue.concurrent(:default).async do
      @rsmgr.manager.getObject(
        @country,
        path: 'countries/1',
        parameters: nil,
        success: ->(op,res) {
          puts "\n op: #{op}"
          puts   "res: #{res}"
          cdq.save
          @status = :success
          resume
        },
        failure: ->(op,err) {
          puts "\n op: #{op}"
          puts   "err: #{err}"
          @status = :failed
          resume
        }
      )
    end

    wait_max 20.0 do
      @status.should != :failed
      @status.should != :unknown
      @status.should == :success

      @country = Country.where(:id).eq(1).first
      @country.should != nil
      puts "@country: #{@country}"
    end
  end
```

Everything works fine, but when I do this line: `@country = Country.where(:id).eq(1).first`, I'm getting the following error:

```
 op: #<RKManagedObjectRequestOperation:0x110dd32e0>
res: #<RKMappingResult:0x16a00a4f0>
2015-01-26 18:35:39.365 T-Restikle Spec[52461:4922023] CoreData: error: (522) I/O error for database at /Users/matts/Library/Developer/CoreSimulator/Devices/FBEF3F22-6C59-4741-9C78-B4A38C568933/data/Containers/Data/Application/88D88DA5-121B-4FF7-8DC0-6C73B2596CC3/Documents/T-Restikle Spec.sqlite.  SQLite error code:522, 'not an error'
2015-01-26 18:35:39.365 T-Restikle Spec[52461:4922023] Core Data: error: -executeRequest: encountered exception = I/O error for database at /Users/matts/Library/Developer/CoreSimulator/Devices/FBEF3F22-6C59-4741-9C78-B4A38C568933/data/Containers/Data/Application/88D88DA5-121B-4FF7-8DC0-6C73B2596CC3/Documents/T-Restikle Spec.sqlite.  SQLite error code:522, 'not an error' with userInfo = {
    NSFilePath = "/Users/matts/Library/Developer/CoreSimulator/Devices/FBEF3F22-6C59-4741-9C78-B4A38C568933/data/Containers/Data/Application/88D88DA5-121B-4FF7-8DC0-6C73B2596CC3/Documents/T-Restikle Spec.sqlite";
    NSSQLiteErrorDomain = 522;
}
 [FAILED - nil.!=(nil) failed]
```

I can see that the REST GET request is working, and I can see that I am getting back a `RKMappingResult` instance, and that `@success == true`. But the contents of `@country` is nil, and CoreData is complaining about the 522 error.

The only things that I can find with respect to CoreData 522 errors related to journaling. Any ideas why that might be popping up here?

**Comment by matthewsinclair** [comment]
Ok, I worked it out. Calling `cdq.reset!` in the `after do` block of the spec seems to be the problem.

**Comment by kemiller** [comment]
Yeah, that's what you need to do.
