### ISSUE TITLE
managedObjectContextDidChange errors with DZNEmptyDataSet and NSFetchedResultsController

### ISSUE THREAD

**Issue by spnkr** [infinitered/cdq#71]
Seems to be incompatible with NSFetchedResultsController and [DZNEmptyDataSet](https://github.com/dzenbot/DZNEmptyDataSet). Causes weird managedObjectContextDidChange errors. Problem may lie with DZNEmptyDataSet?

**Comment by kemiller** [comment]
I know nothing about DZNEmptyDataSet, I'm afraid, so I can't really comment.  If you learn more, let me know.
