### ISSUE TITLE
Ever growing memory usage

### ISSUE THREAD

**Issue by digitalfx** [infinitered/cdq#80]
I'm working on a project that periodically runs a batch of queries to get some information. Profiling it showed an increase in memory usage on each refresh. I've mocked up a project that runs similar queries every second to show this effect: https://www.dropbox.com/s/h751zp025rl7gcq/MemoryTest.zip?dl=0

Here's a screenshot from Instruments with at least 1MB of memory growth added every 10 seconds!
![screen shot 2015-02-16 at 12 53 45](https://cloud.githubusercontent.com/assets/6060466/6212257/e136b0a2-b5da-11e4-9047-462ab3fbfd98.png)

I'm not sure if this is related to CDQ itself or maybe the RubyMotion runtime, but any light on the matter would be great :smiley:

**Comment by digitalfx** [comment]
Just looking for some kind of status update on this issue, regarding whether it's confirmed, expected or something? I'm at a bit of a loss with this in a project right now :cry:

**Comment by kemiller** [comment]
Sorry, no, I haven't had time to really dig into it.  Growing allocations doesn't necessarily indicate a problem, since that number includes scratch space used by the system which it won't necessarily reclaim.  But there may well be a leak; it's just a big task to try to find that.

**Comment by digitalfx** [comment]
Ok, no worries Ken, thanks for responding :smiley:
