### ISSUE TITLE
Uncaught exception when calling cdq.save

### ISSUE THREAD

**Issue by majochoc** [infinitered/cdq#81]
I'm new to cdq so following the greenfield tutorial. I'm using cdq 1.0.1. My app runs fine in the simulator. I can create and save records from the REPL without issue. However, when I try to run on the device I get an uncaught exception for NoMethodErr when calling cdq.save. The error message is:
'undefined method `insertedObjects' for nil:NilClass (NoMethodError)
Looking at the source code for cdq my guess is that this is occurring in set_timestamps in context.rb at line 346. Anyone else seeing this?

**Comment by majochoc** [comment]
Ok I solved this. Yes it was a context issue. I followed the New threading and context guide (https://github.com/infinitered/cdq/wiki/New-Threading-and-Context-Stack-model) for one off workers and this resolved the issue.

**Comment by markrickert** [comment]
Closing. Glad you got it working!
