### ISSUE TITLE
Terminating app due to uncaught exception 'RuntimeError', reason: 'No model file.  Cannot create an NSManagedObjectModel without one. (RuntimeError)

### ISSUE THREAD

**Issue by spnkr** [infinitered/cdq#82]
For some reason I always get this error the first time I `rake device` after changing the app version or app bundle ID. Never have this problem in the simulator.

Any ideas why?

**Comment by spnkr** [comment]
``` ruby
    Deploy ./build/iPhoneOS-8.1-Development/FooBar.ipa
*** Application is running on the device, use ^C to quit.
Feb 24 23:42:44 my-iPhone-6 FooBar[1824] <Warning>: No model file.  Cannot create an NSManagedObjectModel without one. (RuntimeError)
Feb 24 23:42:44 my-iPhone-6 FooBar[1824] <Error>: *** Terminating app due to uncaught exception 'RuntimeError', reason: 'No model file.  Cannot create an NSManagedObjectModel without one. (RuntimeError)

```

**Comment by Bodacious** [comment]
Same here :cry:

**Comment by kemiller** [comment]
Hmm, not sure why that would happen.  It uses the app name as the model file name, but that should not be changing.

**Comment by Bodacious** [comment]
this was completely my fault - I hadn't checked the `.xcdatamodeld` file into my git repo - so it was missing.

A quick `cdq init` fixed it

**Comment by kemiller** [comment]
@spnkr did you resolve it too?

**Comment by fermion** [comment]
I was also seeing this but my case was a little different. My app won't run on the simulator (using https://github.com/jjaffeux/Motionscan and MoodStocks obviates using the simulator) so I'd never simply run `rake`, only `rake device`. I had to run a simulator build in order to generate the assets necessary for things to work.

Not sure there's a way around my issue but I figured I'd mention it :-D

**Comment by kemiller** [comment]
Hmm, I'd never thought of that, but it's a simple matter to make schema:build run before a device build as well as a simulator build.  cdq init adds a hook for simulator build as a convenience, but you can do the same for device.

**Comment by fermion** [comment]
Totally, that's what i did!
