### ISSUE TITLE
uninitialized constant CDQ::Deprecation (NameError)

### ISSUE THREAD

**Issue by paddingtonsbear** [infinitered/cdq#83]
I just switched from cdq `0.1.11` to `1.0.1` and after running `rake` I am presented with the following error
```ruby
*** Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant CDQ::Deprecation (NameError)
```
I already tried running `rake clean` and `rake` and that didn't help. Is anyone else experiencing this same issue

**Comment by kemiller** [comment]
Hmm, I saw that in 1.0.0 but it should have been fixed in 1.0.1.  This week is busy, not sure when I can look into it — another data point would help.

**Comment by paddingtonsbear** [comment]
Any chance you can post a link of the old issue?

**Comment by kemiller** [comment]
old issue?  For 1.0 you mean?  We found it internally; it was never an issue, but it was the same error.

**Comment by paddingtonsbear** [comment]
Any idea how I could be getting this error, any chance you remember how it was found

**Comment by kemiller** [comment]
If you can replicate it in a sample app, that would help.  Something is wrong with the dependency resolution.

**Comment by paddingtonsbear** [comment]
So the problem went away after I set 
```ruby
Motion::Project::App.setup do |app|
  app.detect_dependencies    = true
end
```
I had `detect_dependencies = false` because of dependency issues I faced with the motion_support gem but it looks like the issue was resolved a year ago, guess its my fault for not keeping tabs :disappointed: 
https://github.com/rubymotion/motion-support/commit/c5f03b2ce7a4aa0c3bc986ad34b578b3e86612ca
https://github.com/rubymotion/motion-support/commit/a0a640db2f39d3dbb19985efb53385b15d59314a#commitcomment-5754306

**Comment by paddingtonsbear** [comment]
Quick question. So I have my CoreData stack setup  
```ruby
_store = RKManagedObjectStore.alloc.initWithPersistentStoreCoordinator(cdq.stores.current).tap do |store|
  store.createManagedObjectContexts
  cdq.contexts.push(store.persistentStoreManagedObjectContext)
  cdq.contexts.push(store.mainQueueManagedObjectContext)
end
```

and when I try saving using the new background block

```ruby
cdq.background do
  User.create(name: 'name')

  cdq.save(always_wait: true) # only save the current thread's stack

  # This line throws the following error
  cdq.save(:main) 
end
```

`cdq.save(:main)` throws the following error
```ruby
*** Terminating app due to uncaught exception 'NoMethodError', reason: 'context.rb:170:in `block in 
save:': undefined method `main' for #<CDQ::CDQContextManager:0x118c34f50 ...> (NoMethodError)
```

My question is, how would I propagate my save all the way to `persistentStoreManagedObjectContext`

**Comment by kemiller** [comment]
Ah, RestKit.  Yeah, you can either save directly on RK's main context yourself, or you can name the main context when you push:

```
  cdq.contexts.push(store.mainQueueManagedObjectContext, named: :main)
```

**Comment by kemiller** [comment]
Actually, I should add, since you want to actually save the whole stack, you can also do 

```
cdq.on(:main) { cdq.save }
```

which will save the stack as usual.  `cdq.save(:main)` saves only the named main context.

**Comment by paddingtonsbear** [comment]
thanks ken so I would basically do
```ruby 
_store = RKManagedObjectStore.alloc.initWithPersistentStoreCoordinator(cdq.stores.current).tap do |store|
  store.createManagedObjectContexts
  cdq.contexts.push(store.persistentStoreManagedObjectContext, named: :root)
  cdq.contexts.push(store.mainQueueManagedObjectContext, named: :main)
end
```
and save like this
```ruby
cdq.background do
  User.create(name: 'name')

  cdq.save(always_wait: true) # only save the current thread's stack

  cdq.on(:main) { cdq.save } 
end
```

**Comment by kemiller** [comment]
That's right.
