### ISSUE TITLE
Using a different database, without using cdq.yml...

### ISSUE THREAD

**Issue by digitalmoksha** [infinitered/cdq#93]
This might be a stupid question.  But I want to be able to open a cdq database that is stored inside a package.  Like an iPhoto library is a self-contained package, I want my app to be able to open the database that is stored inside a "library" that I drop on my app.

I know you can use the cdq.yml file to specify a different database name.   A comment in the "config.rb" file, "because class loading order of operations makes it impossible to configure from within your AppDelegate", give the impression that it's not possible to "close" and "open" a different database.

Am I looking at this wrong, does anyone have any suggestions how to accomplish this easily?

Thanks...

**Comment by kemiller** [comment]
I wouldn't say it's not possible, but it's not really optimized for that case.  You'd have to open it yourself and then push it onto CDQ's stack, and then use the `cdq('EntityName')` style of interacting, i.e. no model classes.  It would be a nice feature to have.

**Comment by digitalmoksha** [comment]
Ken, what about passing a CDQConfig object (which is already setup to handle a hash of options) as an option into `cdq.setup`, which would set the `default` config object which the models/stores are built on.  It doesn't seem like the config object gets used until we do a `cdq.setup`.  Would that work?

Then the `cdq.reset!` would clean up/close everything, and we could do another `cdq.setup` with a different config object.

I admit I don't have my head wrapped around all the contexts, models, and stores, so there is probably something fundamental I'm overlooking.

**Comment by kemiller** [comment]
Sounds like a possibility, but you'd have to completely quit whatever you were doing before.  If that's an acceptable constraint, it could work.
